image: docker:latest
services:
  - docker:dind
  - mysql:latest
  
variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: "docker","localstorage"
  MYSQL_ROOT_PASSWORD: "admin"
  MYSQL_DATABASE: "webdev"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: ""
  SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/webdev"
  
stages:
  - build
  
before_script:
  - chmod +x mvnw

build:
  image: maven:3-jdk-8
  stage: build
  script:
    - ./mvnw package
  artifacts:
    paths:
      - build/libs/*.jar